modified pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -25,53 +25,53 @@ jobs:
         uses: actions/checkout@v2
 
       # Install dependencies and run tests for the client application
-      - name: Install frontend
-        working-directory: ./WWA-frontend-master
-        run: |
-          npm install
+      # - name: Install frontend
+      #   working-directory: ./WWA-frontend-master
+      #   run: |
+      #     npm install
 
-      # Install dependencies, export environment variables to be used by application and run tests for the server application
-      - name: Install backend
-        working-directory: ./WWA-backend-master
-        run: |
-          npm install
+      # # Install dependencies, export environment variables to be used by application and run tests for the server application
+      # - name: Install backend
+      #   working-directory: ./WWA-backend-master
+      #   run: |
+      #     npm install
 
-      # Login to Docker Hub using credentials from repository secrets
-      - name: Login to Docker Hub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+      # # Login to Docker Hub using credentials from repository secrets
+      # - name: Login to Docker Hub
+      #   uses: docker/login-action@v1
+      #   with:
+      #     username: ${{ secrets.DOCKER_USERNAME }}
+      #     password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # checking docker login status
-      - name: Check docker login status
-        if: failure()
-        run: echo Docker login process failed.
+      # # checking docker login status
+      # - name: Check docker login status
+      #   if: failure()
+      #   run: echo Docker login process failed.
 
-      # removing old docker images
-      - name: Deleting old docker images
-        run: |
-          docker rmi -f $(docker image ls -a -q)
+      # # removing old docker images
+      # - name: Deleting old docker images
+      #   run: |
+      #     docker rmi -f $(docker image ls -a -q)
 
-      # Build a Docker image for the client application
-      - name: Build Client Docker Image
-        working-directory: ./WWA-frontend-master
-        # Build image with tag pavanvarikolu/wwafrontend-client:latest
-        run: |
-          docker build -t pavanvarikolu/wwafrontend-client:latest .
+      # # Build a Docker image for the client application
+      # - name: Build Client Docker Image
+      #   working-directory: ./WWA-frontend-master
+      #   # Build image with tag pavanvarikolu/wwafrontend-client:latest
+      #   run: |
+      #     docker build -t pavanvarikolu/wwafrontend-client:latest .
 
-      # Build a Docker image for the server application
-      - name: Build Server Docker Image
-        working-directory: ./WWA-backend-master
-        # Build image with tag pavanvarikolu/wwabackend-server:latest
-        run: |
-          docker build -t pavanvarikolu/wwabackend-server:latest .
+      # # Build a Docker image for the server application
+      # - name: Build Server Docker Image
+      #   working-directory: ./WWA-backend-master
+      #   # Build image with tag pavanvarikolu/wwabackend-server:latest
+      #   run: |
+      #     docker build -t pavanvarikolu/wwabackend-server:latest .
 
-      # Push the Docker images to Docker Hub
-      - name: Push Docker Images to Docker Hub
-        run: |
-          docker push pavanvarikolu/wwafrontend-client:latest || true
-          docker push pavanvarikolu/wwabackend-server:latest || true
+      # # Push the Docker images to Docker Hub
+      # - name: Push Docker Images to Docker Hub
+      #   run: |
+      #     docker push pavanvarikolu/wwafrontend-client:latest || true
+      #     docker push pavanvarikolu/wwabackend-server:latest || true
 
   iac-build-and-deploy:
     runs-on: ubuntu-latest
@@ -93,47 +93,82 @@ jobs:
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: "1.1.7"
-
-      - name: Running Terraform Commands
-        id: running-terraform-commands
-        working-directory: ./terraform
+      - name: Terraform Init, Format, Validate
         run: |
-          terraform init
-          terraform validate -no-color
-          terraform plan 
-          terraform apply -auto-approve | tee terraform_output.txt 
-          TARGET_URL=$(terraform output ec2_public_ip)
-          echo "::set-output name=target::$TARGET_URL"
-          echo "EC2 IP Address: $TARGET_URL"  # Print EC2 IP in the pipeline
-          echo "##[group]Terraform Output"
-          cat terraform_output.txt
-          echo "##[endgroup]"
-      
-
-  zap_scan:
-    name: OWASP-ZAP integration 
+            terraform init
+            terraform fmt -check
+            terraform validate -no-color
+        working-directory: terraform-infra
+          
+      - name: Terraform Plan
+        run: terraform plan --var-file=dev.terraform.tfvars
+        working-directory: terraform-infra
+      - name: Terraform Apply
+        run: terraform apply --auto-approve --var-file=dev.terraform.tfvars
+        working-directory: terraform-infra
+          
+    
+  infrastructure-audit:
+    name: infrastructure-audit
     runs-on: ubuntu-latest
-    permissions: write-all
-    needs: iac-build-and-deploy
+    if: ${{ github.event.inputs.infrastructure-audit == 'yes' }}
+    
     steps:
-      - name: Wait for 2 minutes
-        run: sleep 120
-      - name: Checkout repository
-        uses: actions/checkout@v2
-        with:
-          ref: main
-      - name: ZAP Scan
-        uses: zaproxy/action-baseline@v0.11.0
-        with:
-       #   token: ${{ secrets.GITHUB_TOKEN }}
-          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
-          target: 'http://${{ needs.iac-build-and-deploy.outputs.target_url }}:3000'
-          rules_file_name: '.zap/rules.tsv'
-          cmd_options: '-a'
-      - name: Upload ZAP Scan Report
-        uses: actions/upload-artifact@v2
-        with:
-          name: zap-report
-          path: |
-            report_html.html
-            report_json.json
+        - name: Checkout
+          uses: actions/checkout@v3
+    
+        - name: Install tfsec
+          run: |
+            wget -q $(wget -qO- https://api.github.com/repos/aquasecurity/tfsec/releases/latest | grep -o -E "https://[^\"]*linux_amd64.tar.gz") -O tfsec.tar.gz
+            tar -xzf tfsec.tar.gz
+            sudo install tfsec /usr/local/bin/
+          working-directory: terraform-infra
+    
+        - name: Run tfsec
+          run: tfsec . --exclude-downloaded-modules --tfvars-file dev.terraform.tfvars
+          working-directory: terraform-infra
+          continue-on-error: true
+    
+        - name: Install Checkov
+          run: pip install checkov
+    
+        - name: Run Kubernetes YAMLS files Scan
+          run: |
+            checkov -d . --framework kubernetes --download-external-modules true
+          continue-on-error: true
+    
+        - name: Run Checkov IAC Scan
+          run: |
+            checkov -d . --framework terraform --download-external-modules true
+          working-directory: terraform-infra 
+          continue-on-error: true
+          
+    
+      
+  # zap_scan:
+  #   name: OWASP-ZAP integration 
+  #   runs-on: ubuntu-latest
+  #   permissions: write-all
+  #   needs: iac-build-and-deploy
+  #   steps:
+  #     - name: Wait for 2 minutes
+  #       run: sleep 120
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v2
+  #       with:
+  #         ref: main
+  #     - name: ZAP Scan
+  #       uses: zaproxy/action-baseline@v0.11.0
+  #       with:
+  #      #   token: ${{ secrets.GITHUB_TOKEN }}
+  #         docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
+  #         target: 'http://${{ needs.iac-build-and-deploy.outputs.target_url }}:3000'
+  #         rules_file_name: '.zap/rules.tsv'
+  #         cmd_options: '-a'
+  #     - name: Upload ZAP Scan Report
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: zap-report
+  #         path: |
+  #           report_html.html
+  #           report_json.json
